"
" dotvim : https://github.com/dotphiles/dotvim
"
" gvimrc config
"
" Authors:
"   Ben O'Hara <bohara@gmail.com>
"

if has('mac')
  " set guifont=Menlo:h12
  set guifont=Inconsolata\ for\ Powerline:h13
  " Don't display the menu or toolbar. Just the screen.
  set guioptions-=m
  set guioptions-=T
  set lines=44 columns=180 " fullscreen macbookpro 13'

elseif has('unix')
  set guifont="DejaVu Sans Mono 10"
endif
